language: cpp

matrix:
  include:
    - stage: test
      os: linux
      dist: xenial
      sudo: required
      env: TASK=TestMaBoSS
    - stage: test
      os: osx
      env: TASK=TestMaBoSS

before_install:
  if [ $TASK = 'TestMaBoSS' ]; then
    if [ $TRAVIS_OS_NAME = 'osx' ]; then
        brew install flex bison;
        pip install numpy;
      else
        sudo apt-get -qq update && sudo apt-get install -y flex bison;
        sudo pip install numpy;
      fi
  fi
install:
  if [ $TASK = 'TestMaBoSS' ]; then
    bash -c "cd engine/src; make install";

  fi

script:
  if [ $TASK = 'TestMaBoSS' ]; then
      bash -c "cd engine/tests; bash ./test-cellcycle.sh";
      bash -c "cd engine/tests; bash ./test-ensemble.sh";

  fi
